# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160205_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish',
            new_name='published_date',
        ),
    ]
